version: '3.5'

services:
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: jobtest_phpmyadmin
        labels:
            - "traefik.frontend.rule=Host:phpmyadmin.jobtest.fr"
        environment:
            - PMA_HOST=jobtest_mysql
