version: '3.5'

volumes:
    db: ~

networks:
    default:
        name: jobtest

services:
    app:
        build:
            context: docker/app
        container_name: jobtest_app
        volumes:
            - .:/var/www/html
            - ./docker/app/config/app.ini:/usr/local/etc/php/conf.d/app.ini:ro

    front:
        image: nginx:1.14-alpine
        container_name: jobtest_front
        depends_on:
            - app
        volumes:
            - ./docker/front/config/app.conf:/etc/nginx/conf.d/app.conf
            - ./public:/var/www/html/public
        labels:
            - "traefik.frontend.rule=Host:local.jobtest.fr"
        networks:
            default:
                aliases:
                    - local.jobtest.fr

    cli:
        build:
            context: docker/cli
        container_name: jobtest_cli
        working_dir: /var/www/html
        volumes:
            - .:/var/www/html
            - ./docker/cli/config/cli.ini:/usr/local/etc/php/conf.d/cli.ini:ro

    redis:
        image: redis:alpine
        container_name: jobtest_redis

    mysql:
        image: mariadb:10.3
        container_name: jobtest_mysql
        environment:
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
            - MYSQL_DATABASE=jobtest
        volumes:
            - db:/var/lib/mysql

    node:
        image: node:10.11-alpine
        container_name: jobtest_node
        working_dir: /var/www/html
        volumes:
            - .:/var/www/html
